apiVersion: v1
kind: pod
metadata: 
  name: simple-pod
  namespace: roboshop
labels:
  environment: Dev
  app: nginx

spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80
