apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
  namespace: project-1
  
spec:
  containers:
  - name: nginx
    image: ngins
    ports:
      - containerPort: 80
  - name: redis
    image: redis
    ports:
    - containerPort: 6379
