apiVersion: v1
kind: apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
  namespace: project-1
  
spec:
  containers:
  - name: nginx
    image: ngins
    resources:
      limits:
        memory: "18Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
    - name: redis
    image: redis
    resources:
      limits:
        memory: "18Mi"
        cpu: "100m"
    ports:
      - containerPort: 6379
