apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: web
  ports:
  - port: 8081
    targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deployment
  annotations:
    kubernetes.io/change-cause: "version 1.21.3"

spec:
  replicas: 3
  selector:
    matchLabels: 
      app: web
  template:
    metadata:
      name: nginx-pod
      labels:
        env: dev
        app: web
    spec:
      containers:
        - name: nginx-pod
          image: nginx:1.21.3
          ports:
            - containerPort: 80