apiVersion: v1
kind: Pod
metadata: 
  name: simple-pod
  namespace: project-1
labels:
  environment: dev
  app: nginx
  
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80